### ISSUE TITLE
Problems in a multithread-usage

### ISSUE THREAD

**Issue by db0x** [SvenEwald/xmlbeam#47]
It seems, that the lib (or parts) are not thread-safe. 

If you use it in an spring-boot container behind RestController, the lib produces StackOverflowError if this is called asynchronous from other systems.

Caused by: java.lang.StackOverflowError: null
	at org.xmlbeam.util.intern.DOMHelper.fillNSMapWithPrefixesDeclaredInElement(DOMHelper.java:126) ~[xmlprojector-1.4.13.jar:na]
	at org.xmlbeam.util.intern.DOMHelper.fillNSMapWithPrefixesDeclaredInElement(DOMHelper.java:143) ~[xmlprojector-1.4.13.jar:na]

**Comment by SvenEwald** [comment]
This is a known issue. I could not rely on the thread-saveness in the underlying DOM implementation. You may have to create the XBProjector with the Flag "SYNCHRONIZE_ON_DOCUMENTS". This will make all calls to projection interfaces thread-safe. Please tell me, if this solves your issue.

**Comment by db0x** [comment]
Nice :+1:  the flag helped ... Thank you :) 

And yes, more documentation will be helpful.

**Comment by SvenEwald** [comment]
Added "thread safety" to FAQ.
