### ISSUE TITLE
NullPointerException when setting fresh (empty) child projection onto a parent projection

### ISSUE THREAD

**Issue by zhsc** [SvenEwald/xmlbeam#53]
Seeing this error where when you first create a projection and haven't called any setters on it it throws an NullPointerException when you set it onto a child.

Here's a test case:
```
import static org.junit.Assert.assertEquals;

import org.junit.Test;
import org.xmlbeam.XBProjector;
import org.xmlbeam.XBProjector.Flags;
import org.xmlbeam.annotation.XBWrite;

public class TestSetEmptyChildProjection {

	public interface Child {
		@XBWrite("ChildData")
		void setData(String data);
	}
	
	public interface ParentWithRootElement {
		@XBWrite("Root/ParentData")
		void setData(String data);
		
		@XBWrite("Root/Child")
		void setChild(Child child);
	}

	@Test
	public void testSetEmptyChildNonEmptyParent() {
		XBProjector projector = new XBProjector(Flags.TO_STRING_RENDERS_XML);
		
		ParentWithRootElement parent = projector.projectEmptyDocument(ParentWithRootElement.class);
		parent.setData("parent data...");
		
		Child child = projector.projectEmptyDocument(Child.class);
//		child.setData(""); // Uncommenting fixes NPE error (assertion will fail of course, but that's fine)
		
		parent.setChild(child);
		
		/* Throws
		java.lang.NullPointerException
			at org.xmlbeam.ProjectionInvocationHandler$WriteInvocationHandler.invokeProjection(ProjectionInvocationHandler.java:659)
			at org.xmlbeam.ProjectionInvocationHandler$ProjectionMethodInvocationHandler.invoke(ProjectionInvocationHandler.java:206)
			at org.xmlbeam.ProjectionInvocationHandler.invoke(ProjectionInvocationHandler.java:879)
			at com.sun.proxy.$Proxy5.setChild(Unknown Source)
		 */
		
		assertEquals(
				  "<Root>\n"
				+ "   <ParentData>parent data...</ParentData>\n"
				+ "</Root>",
				parent.toString());
		
		System.out.println("Result: " + parent);
	}

**Comment by SvenEwald** [comment]
Actually... this can not work. Setting an empty document means that there is no (root) element to be set. `projector.projectEmptyElement("child",Child.class)` will work here. Nevertheless, this case deserves a better error message ;-)
