### ISSUE TITLE
NPE during createTransformer and prettyprinting is ON (OpenJDK 11.0.3 - after upgrading v1.2.40 to 1.2.42) 

### ISSUE THREAD

**Issue by zaffranad** [SvenEwald/xmlbeam#62]
Hi,

We performed an upgrade of the xmlbeam lib on our spring boot application, from 1.2.40 to 1.2.42.
This causes the use of :

```java
return new XBProjector(
                    new DefaultXMLFactoriesConfig()
                            .setNamespacePhilosophy(AGNOSTIC)
            ).asString(request)
//where request is an xmlbeam annotated interface 
```
to throw an NPE:

```
Caused by: org.xmlbeam.exceptions.XBException: Error on creating transformer
	at org.xmlbeam.config.DefaultXMLFactoriesConfig.createTransformer(DefaultXMLFactoriesConfig.java:242)
	at org.xmlbeam.XBProjector$ConfigBuilder.createTransformer(XBProjector.java:255)
	at org.xmlbeam.util.intern.DOMHelper.toXMLString(DOMHelper.java:591)
	at org.xmlbeam.DefaultDOMAccessInvoker.asString(DefaultDOMAccessInvoker.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.xmlbeam.ProjectionInvocationHandler$ReflectionInvoker.invoke(ProjectionInvocationHandler.java:111)
	at org.xmlbeam.ProjectionInvocationHandler.invoke(ProjectionInvocationHandler.java:878)
	at com.sun.proxy.$Proxy60.asString(Unknown Source)
	at org.xmlbeam.XBProjector.asString(XBProjector.java:788)
	... 68 more
Caused by: javax.xml.transform.TransformerConfigurationException: java.net.MalformedURLException
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1059)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:817)
	at org.xmlbeam.config.DefaultXMLFactoriesConfig.createTransformer(DefaultXMLFactoriesConfig.java:226)
	... 82 more
Caused by: java.net.MalformedURLException
	at java.base/java.net.URL.<init>(URL.java:661)
	at java.base/java.net.URL.<init>(URL.java:523)
	at java.base/java.net.URL.<init>(URL.java:470)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:651)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:150)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:860)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.parse(Parser.java:429)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.parse(Parser.java:512)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:476)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:570)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1018)
	... 84 more
Caused by: java.lang.NullPointerException
	at java.base/java.net.URL.<init>(URL.java:567)
	... 98 more
```

When debugging lib sources, the following lines, which appeared with the release 1.2.41, are the root cause of the NPE:

```java
// Class: DefaultXMLFactoriesConfig.java
Transformer transformer = isPrettyPrinting && (ReflectionHelper.JAVA_VERSION > 8) ? transformerFactory.newTransformer(new StreamSource(getClass().getResourceAsStream("prettyprint.xslt"))) : transformerFactory.newTransformer();
```

As a matter of fact, the file prettyprint.xslt is not accessible using the getResourceAsStream as it looks like it is not within the jar file...
As long as we turn the prettyprinting mode OFF, the NPE does not appear.

The prettyprint.xslt is located in main/java (not main/resources) which can explain the fact it is not in the JAR:
![image](https://user-images.githubusercontent.com/4168542/163574627-a59206f9-cfb0-46c3-ab86-9597a8098aa2.png)

---
Alongside this problem, we observed that, after picking the file prettyprint.xslt from your sources and copied it into our classpath, the XBProjector.asString method worked, but the XML generated has lost his namespace prefixes on all its tags:

if the XML template used is something like this:
```xml
<msg:Envelope xmlns:msg="http://message/url" xmlns:test="http://test/url">
    <msg:Body>
        <test:Attribute>
            <test:Code>0</test:Code>
        </test:Attribute>
    </msg:Body>
</msg:Envelope>
```

the result is:
```xml
<Envelope xmlns:msg="http://message/url" xmlns:test="http://test/url">
    <Body>
        <Attribute>
            <Code>0</Code>
        </Attribute>
    </Body>
</Envelope>
```

Any idea of the reason ?

Thank you very much for your help

**Comment by SvenEwald** [comment]
Thank you very much for your report. The cause is that packaging is broken and the xslt is missing.
Release 1.4.23 will have the fix and is relased now.

**Comment by zaffranad** [comment]
Thank you, that's a good news.
Do you have an idea about the behaviour concerning the namespaces removed after projection?

> 
> Alongside this problem, we observed that, after picking the file prettyprint.xslt from your sources and copied it into our classpath, the XBProjector.asString method worked, but the XML generated has lost his namespace prefixes on all its tags:
> 
> if the XML template used is something like this:
> 
> <msg:Envelope xmlns:msg="http://message/url" xmlns:test="http://test/url">
>     <msg:Body>
>         <test:Attribute>
>             <test:Code>0</test:Code>
>         </test:Attribute>
>     </msg:Body>
> </msg:Envelope>
> the result is:
> 
> <Envelope xmlns:msg="http://message/url" xmlns:test="http://test/url">
>     <Body>
>         <Attribute>
>             <Code>0</Code>
>         </Attribute>
>     </Body>
> </Envelope>
> Any idea of the reason ?
> 
> Thank you very much for your help

**Comment by SvenEwald** [comment]
I can confirm this bug. Handled in #63
